import React, { useState } from "react";

function Countrylist({ getCountryA }) {
  const countries = [
    ["AF", "Afghanistan", "afn"],
    ["AL", "Albania", "all"],
    ["DZ", "Algeria", "dzd"],
    ["AS", "American Samoa", "usd"],
    ["AD", "Andorra", "eur"],
    ["AO", "Angola", "aoa"],
    ["AI", "Anguilla", "xcd"],
    ["AQ", "Antarctica", "n/a"],
    ["AG", "Antigua and Barbuda", "xcd"],
    ["AR", "Argentina", "ars"],
    ["AM", "Armenia", "amd"],
    ["AW", "Aruba", "awg"],
    ["AU", "Australia", "aud"],
    ["AT", "Austria", "eur"],
    ["AZ", "Azerbaijan", "azn"],
    ["BS", "Bahamas", "bsd"],
    ["BH", "Bahrain", "bhd"],
    ["BD", "Bangladesh", "bdt"],
    ["BB", "Barbados", "bbd"],
    ["BY", "Belarus", "byn"],
    ["BE", "Belgium", "eur"],
    ["BZ", "Belize", "bzd"],
    ["BJ", "Benin", "xof"],
    ["BM", "Bermuda", "bmd"],
    ["BT", "Bhutan", "btn"],
    ["BO", "Bolivia", "bob"],
    ["BA", "Bosnia and Herzegovina", "bam"],
    ["BW", "Botswana", "bwp"],
    ["BV", "Bouvet Island", "nok"],
    ["BR", "Brazil", "brl"],
    ["IO", "British Indian Ocean Territory", "usd"],
    ["BN", "Brunei Darussalam", "bnd"],
    ["BG", "Bulgaria", "bgn"],
    ["BF", "Burkina Faso", "xof"],
    ["BI", "Burundi", "bif"],
    ["CV", "Cabo Verde", "cve"],
    ["KH", "Cambodia", "khr"],
    ["CM", "Cameroon", "xaf"],
    ["CA", "Canada", "cad"],
    ["KY", "Cayman Islands", "kyd"],
    ["CF", "Central African Republic", "xaf"],
    ["TD", "Chad", "xaf"],
    ["CL", "Chile", "clp"],
    ["CN", "China", "cny"],
    ["CX", "Christmas Island", "aud"],
    ["CC", "Cocos (Keeling) Islands", "aud"],
    ["CO", "Colombia", "cop"],
    ["KM", "Comoros", "kmf"],
    ["CG", "Congo", "xaf"],
    ["CD", "Congo, Democratic Republic of the", "cdf"],
    ["CK", "Cook Islands", "nzd"],
    ["CR", "Costa Rica", "crc"],
    ["CI", "Côte d'Ivoire", "xof"],
    ["HR", "Croatia", "hrk"],
    ["CU", "Cuba", "cup"],
    ["CY", "Cyprus", "eur"],
    ["CZ", "Czechia", "czk"],
    ["DK", "Denmark", "dkk"],
    ["DJ", "Djibouti", "djf"],
    ["DM", "Dominica", "xcd"],
    ["DO", "Dominican Republic", "dop"],
    ["EC", "Ecuador", "usd"],
    ["EG", "Egypt", "egp"],
    ["SV", "El Salvador", "usd"],
    ["GQ", "Equatorial Guinea", "xaf"],
    ["ER", "Eritrea", "ern"],
    ["EE", "Estonia", "eur"],
    ["SZ", "Eswatini", "szl"],
    ["ET", "Ethiopia", "etb"],
    ["FK", "Falkland Islands (Malvinas)", "fkp"],
    ["FO", "Faroe Islands", "dkk"],
    ["FJ", "Fiji", "fjd"],
    ["FI", "Finland", "eur"],
    ["FR", "France", "eur"],
    ["GF", "French Guiana", "eur"],
    ["PF", "French Polynesia", "xpf"],
    ["TF", "French Southern Territories", "eur"],
    ["GA", "Gabon", "xaf"],
    ["GM", "Gambia", "gmd"],
    ["GE", "Georgia", "gel"],
    ["DE", "Germany", "eur"],
    ["GH", "Ghana", "ghs"],
    ["GI", "Gibraltar", "gip"],
    ["GR", "Greece", "eur"],
    ["GL", "Greenland", "dkk"],
    ["GD", "Grenada", "xcd"],
    ["GP", "Guadeloupe", "eur"],
    ["GU", "Guam", "usd"],
    ["GT", "Guatemala", "gtq"],
    ["GG", "Guernsey", "gbp"],
    ["GN", "Guinea", "gnf"],
    ["GW", "Guinea-Bissau", "xof"],
    ["GY", "Guyana", "gyd"],
    ["HT", "Haiti", "htg"],
    ["HM", "Heard Island and McDonald Islands", "aud"],
    ["VA", "Holy See", "eur"],
    ["HN", "Honduras", "hnl"],
    ["HK", "Hong Kong", "hkd"],
    ["HU", "Hungary", "huf"],
    ["IS", "Iceland", "isk"],
    ["IN", "India", "inr"],
    ["ID", "Indonesia", "idr"],
    ["IR", "Iran", "irr"],
    ["IQ", "Iraq", "iqd"],
    ["IE", "Ireland", "eur"],
    ["IM", "Isle of Man", "gbp"],
    ["IL", "Israel", "ils"],
    ["IT", "Italy", "eur"],
    ["JM", "Jamaica", "jmd"],
    ["JP", "Japan", "jpy"],
    ["JE", "Jersey", "gbp"],
    ["JO", "Jordan", "jod"],
    ["KZ", "Kazakhstan", "kzt"],
    ["KE", "Kenya", "kes"],
    ["KI", "Kiribati", "aud"],
    ["KP", "Korea, Democratic People's Republic of", "kpw"],
    ["KR", "Korea, Republic of", "krw"],
    ["KW", "Kuwait", "kwd"],
    ["KG", "Kyrgyzstan", "kgs"],
    ["LA", "Lao People's Democratic Republic", "lak"],
    ["LV", "Latvia", "eur"],
    ["LB", "Lebanon", "lbp"],
    ["LS", "Lesotho", "lsl"],
    ["LR", "Liberia", "lrd"],
    ["LY", "Libya", "lyd"],
    ["LI", "Liechtenstein", "chf"],
    ["LT", "Lithuania", "eur"],
    ["LU", "Luxembourg", "eur"],
    ["MO", "Macao", "mop"],
    ["MG", "Madagascar", "mga"],
    ["MW", "Malawi", "mwk"],
    ["MY", "Malaysia", "myr"],
    ["MV", "Maldives", "mvr"],
    ["ML", "Mali", "xof"],
    ["MT", "Malta", "eur"],
    ["MH", "Marshall Islands", "usd"],
    ["MQ", "Martinique", "eur"],
    ["MR", "Mauritania", "mru"],
    ["MU", "Mauritius", "mur"],
    ["YT", "Mayotte", "eur"],
    ["MX", "Mexico", "mxn"],
    ["FM", "Micronesia", "usd"],
    ["MD", "Moldova", "mdl"],
    ["MC", "Monaco", "eur"],
    ["MN", "Mongolia", "mnt"],
    ["ME", "Montenegro", "eur"],
    ["MS", "Montserrat", "xcd"],
    ["MA", "Morocco", "mad"],
    ["MZ", "Mozambique", "mzn"],
    ["MM", "Myanmar", "mmk"],
    ["NA", "Namibia", "nad"],
    ["NR", "Nauru", "aud"],
    ["NP", "Nepal", "npr"],
    ["NL", "Netherlands", "eur"],
    ["NC", "New Caledonia", "xpf"],
    ["NZ", "New Zealand", "nzd"],
    ["NI", "Nicaragua", "nio"],
    ["NE", "Niger", "xof"],
    ["NG", "Nigeria", "ngn"],
    ["NU", "Niue", "nzd"],
    ["NF", "Norfolk Island", "aud"],
    ["MP", "Northern Mariana Islands", "usd"],
    ["NO", "Norway", "nok"],
    ["OM", "Oman", "omr"],
    ["PK", "Pakistan", "pkr"],
    ["PW", "Palau", "usd"],
    ["PS", "Palestine", "ils"],
    ["PA", "Panama", "pab"],
    ["PG", "Papua New Guinea", "pgk"],
    ["PY", "Paraguay", "pyg"],
    ["PE", "Peru", "pen"],
    ["PH", "Philippines", "php"],
    ["PN", "Pitcairn", "nzd"],
    ["PL", "Poland", "pln"],
    ["PT", "Portugal", "eur"],
    ["PR", "Puerto Rico", "usd"],
    ["QA", "Qatar", "qar"],
    ["RE", "Réunion", "eur"],
    ["RO", "Romania", "ron"],
    ["RU", "Russian Federation", "rub"],
    ["RW", "Rwanda", "rwf"],
    ["BL", "Saint Barthélemy", "eur"],
    ["SH", "Saint Helena", "shp"],
    ["KN", "Saint Kitts and Nevis", "xcd"],
    ["LC", "Saint Lucia", "xcd"],
    ["MF", "Saint Martin (French part)", "eur"],
    ["PM", "Saint Pierre and Miquelon", "eur"],
    ["VC", "Saint Vincent and the Grenadines", "xcd"],
    ["WS", "Samoa", "wst"],
    ["SM", "San Marino", "eur"],
    ["ST", "Sao Tome and Principe", "stn"],
    ["SA", "Saudi Arabia", "sar"],
    ["SN", "Senegal", "xof"],
    ["RS", "Serbia", "rsd"],
    ["SC", "Seychelles", "scr"],
    ["SL", "Sierra Leone", "sll"],
    ["SG", "Singapore", "sgd"],
    ["SX", "Sint Maarten (Dutch part)", "ang"],
    ["SK", "Slovakia", "eur"],
    ["SI", "Slovenia", "eur"],
    ["SB", "Solomon Islands", "sbd"],
    ["SO", "Somalia", "sos"],
    ["ZA", "South Africa", "zar"],
    ["GS", "South Georgia and the South Sandwich Islands", "gbp"],
    ["SS", "South Sudan", "ssp"],
    ["ES", "Spain", "eur"],
    ["LK", "Sri Lanka", "lkr"],
    ["SD", "Sudan", "sdg"],
    ["SR", "Suriname", "srd"],
    ["SJ", "Svalbard and Jan Mayen", "nok"],
    ["SE", "Sweden", "sek"],
    ["CH", "Switzerland", "chf"],
    ["SY", "Syrian Arab Republic", "syp"],
    ["TW", "Taiwan", "twd"],
    ["TJ", "Tajikistan", "tjs"],
    ["TZ", "Tanzania", "tzs"],
    ["TH", "Thailand", "thb"],
    ["TL", "Timor-Leste", "usd"],
    ["TG", "Togo", "xof"],
    ["TK", "Tokelau", "nzd"],
    ["TO", "Tonga", "top"],
    ["TT", "Trinidad and Tobago", "ttd"],
    ["TN", "Tunisia", "tnd"],
    ["TR", "Turkey", "try"],
    ["TM", "Turkmenistan", "tmt"],
    ["TC", "Turks and Caicos Islands", "usd"],
    ["TV", "Tuvalu", "aud"],
    ["UG", "Uganda", "ugx"],
    ["UA", "Ukraine", "uah"],
    ["AE", "United Arab Emirates", "aed"],
    ["GB", "United Kingdom of Great Britain and Northern Ireland", "gbp"],
    ["UM", "United States Minor Outlying Islands", "usd"],
    ["UY", "Uruguay", "uyu"],
    ["UZ", "Uzbekistan", "uzs"],
    ["VU", "Vanuatu", "vuv"],
    ["VE", "Venezuela", "ves"],
    ["VN", "Viet Nam", "vnd"],
    ["VG", "Virgin Islands (British)", "usd"],
    ["VI", "Virgin Islands (U.S.)", "usd"],
    ["WF", "Wallis and Futuna", "xpf"],
    ["EH", "Western Sahara", "mad"],
    ["YE", "Yemen", "yer"],
    ["ZM", "Zambia", "zmw"],
    ["ZW", "Zimbabwe", "usd"],
  ];
  const [selected, setSelected] = useState("");
  const handleSelect = (e) => {
    let value = e.target.value;
    setSelected(value);
    let newValue = value.split(",");
    let data = [...newValue];
    getCountryA(data);
    // console.log("data", data);
    // console.log("full array ", newValue);
    // console.log("for Country Name newValue[1]", newValue[1]);
    // console.log("for flags newValue[0]", newValue[0]);
    // console.log("for currency code newValue[2]", newValue[2]);
  };
  return (
    <>
      <select
        name="currency"
        id="currency"
        value={selected}
        onChange={handleSelect}
      >
        <option key="Select" value="">
          Please Select a Country
        </option>
        {countries.map((country, index) => (
          <option key={country[0]} value={[country[0], country[1], country[2]]}>
            {country[1]} {"      "} :{country[0]} {"      "} : {country[2]}{" "}
          </option>
        ))}
      </select>
    </>
  );
}

export default Countrylist;
